// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zakozdovptjhijqpvjbb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpha296ZG92cHRqaGlqcXB2amJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUzNTAxOTYsImV4cCI6MjA1MDkyNjE5Nn0.ObSokyFUfKjQUwLk_KZuULny_NQV5DG19RNobnAQkQ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);